site_name: Fusion en Español
site_description: Una biblioteca reactiva moderna, construida específicamente para Roblox y Luau.
site_url: https://vexot.github.io/Fusion/
repo_name: Elttob/Fusion
repo_url: https://github.com/Elttob/Fusion

theme:
  name: material
  language: es
  custom_dir: docs/assets/overrides
  logo: assets/logo-dark.svg
  favicon: assets/logo-dark.svg
  palette:
    scheme: fusion-dark
    primary: black
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/fusion.css

nav:
  - Inicio: index.md
  - Tutoriales:
    - Empezar: tutorials/index.md
    - Fundamentos:
      - Creando UI: tutorials/fundamentals/creating-ui.md
      - Manejando Eventos: tutorials/fundamentals/handling-events.md
      - Guardando States: tutorials/fundamentals/storing-state.md
      - Cómputos: tutorials/fundamentals/computations.md
      - Cambiando Propiedades: tutorials/fundamentals/changing-properties.md
      - Cambiando Children: tutorials/fundamentals/changing-children.md
      - "Proyecto 1: Contando Clics": tutorials/fundamentals/project-1.md
    - Otros Fundamentos:
      - Componentes: tutorials/further-basics/components.md
      - Arrays y Listas: tutorials/further-basics/arrays-and-lists.md
      - Compatibilidad: tutorials/further-basics/compatibility.md
      - "Proyecto 2: Lista To-Do": tutorials/further-basics/project-2.md
    - Animación:
      - Tweens: tutorials/animation/tweens.md
      - Springs: tutorials/animation/springs.md
      - "Proyecto 3: Switches": tutorials/animation/project-3.md
  - Ejemplos:
    - Inicio: examples/index.md
  - Referencia del API:
    - Inicio: api-reference/index.md
    - Errores y Mensajes: api-reference/errors-and-messages.md
    - Instancias:
      - New: api-reference/api/new.md
      - Children: api-reference/api/children.md
      - OnEvent: api-reference/api/onevent.md
      - OnChange: api-reference/api/onchange.md
    - Gestión de Estados:
      - State: api-reference/api/state.md
      - Computed: api-reference/api/computed.md
      - ComputedPairs: api-reference/api/computedpairs.md
      - Compat: api-reference/api/compat.md
    - Animación:
      - Tween: api-reference/api/tween.md
      - Spring: api-reference/api/spring.md
  - Extras:
    - Inicio: extras/index.md
    - Fondos: extras/backgrounds.md

extra:
  social:
    - icon: fontawesome/regular/copyright
      link: https://github.com/Elttob/Fusion
      name: Original Repo

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false

plugins:
  - search
